//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34011.
// 
#pragma warning disable 1591

namespace RRHH.serviciosUPC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrabajadorWSImplServiceSoapBinding", Namespace="http://impl.ws.servicesweb.rrhhintegration.com/")]
    public partial class TrabajadorWSImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback registrarTrabajadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTodosOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTrabajadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarTrabajadorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrabajadorWSImplService() {
            this.Url = global::RRHH.Properties.Settings.Default.RRHH_serviciosUPC_TrabajadorWSImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event registrarTrabajadorCompletedEventHandler registrarTrabajadorCompleted;
        
        /// <remarks/>
        public event obtenerTodosCompletedEventHandler obtenerTodosCompleted;
        
        /// <remarks/>
        public event eliminarTrabajadorCompletedEventHandler eliminarTrabajadorCompleted;
        
        /// <remarks/>
        public event actualizarTrabajadorCompletedEventHandler actualizarTrabajadorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.servicesweb.rrhhintegration.com/", ResponseNamespace="http://ws.servicesweb.rrhhintegration.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string registrarTrabajador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trabajador request) {
            object[] results = this.Invoke("registrarTrabajador", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registrarTrabajadorAsync(trabajador request) {
            this.registrarTrabajadorAsync(request, null);
        }
        
        /// <remarks/>
        public void registrarTrabajadorAsync(trabajador request, object userState) {
            if ((this.registrarTrabajadorOperationCompleted == null)) {
                this.registrarTrabajadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarTrabajadorOperationCompleted);
            }
            this.InvokeAsync("registrarTrabajador", new object[] {
                        request}, this.registrarTrabajadorOperationCompleted, userState);
        }
        
        private void OnregistrarTrabajadorOperationCompleted(object arg) {
            if ((this.registrarTrabajadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarTrabajadorCompleted(this, new registrarTrabajadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.servicesweb.rrhhintegration.com/", ResponseNamespace="http://ws.servicesweb.rrhhintegration.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trabajador[] obtenerTodos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string request, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
            object[] results = this.Invoke("obtenerTodos", new object[] {
                        request,
                        arg1});
            return ((trabajador[])(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTodosAsync(string request, string arg1) {
            this.obtenerTodosAsync(request, arg1, null);
        }
        
        /// <remarks/>
        public void obtenerTodosAsync(string request, string arg1, object userState) {
            if ((this.obtenerTodosOperationCompleted == null)) {
                this.obtenerTodosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTodosOperationCompleted);
            }
            this.InvokeAsync("obtenerTodos", new object[] {
                        request,
                        arg1}, this.obtenerTodosOperationCompleted, userState);
        }
        
        private void OnobtenerTodosOperationCompleted(object arg) {
            if ((this.obtenerTodosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTodosCompleted(this, new obtenerTodosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.servicesweb.rrhhintegration.com/", ResponseNamespace="http://ws.servicesweb.rrhhintegration.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eliminarTrabajador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string request) {
            object[] results = this.Invoke("eliminarTrabajador", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTrabajadorAsync(string request) {
            this.eliminarTrabajadorAsync(request, null);
        }
        
        /// <remarks/>
        public void eliminarTrabajadorAsync(string request, object userState) {
            if ((this.eliminarTrabajadorOperationCompleted == null)) {
                this.eliminarTrabajadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTrabajadorOperationCompleted);
            }
            this.InvokeAsync("eliminarTrabajador", new object[] {
                        request}, this.eliminarTrabajadorOperationCompleted, userState);
        }
        
        private void OneliminarTrabajadorOperationCompleted(object arg) {
            if ((this.eliminarTrabajadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTrabajadorCompleted(this, new eliminarTrabajadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.servicesweb.rrhhintegration.com/", ResponseNamespace="http://ws.servicesweb.rrhhintegration.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string actualizarTrabajador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] trabajador request) {
            object[] results = this.Invoke("actualizarTrabajador", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarTrabajadorAsync(trabajador request) {
            this.actualizarTrabajadorAsync(request, null);
        }
        
        /// <remarks/>
        public void actualizarTrabajadorAsync(trabajador request, object userState) {
            if ((this.actualizarTrabajadorOperationCompleted == null)) {
                this.actualizarTrabajadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarTrabajadorOperationCompleted);
            }
            this.InvokeAsync("actualizarTrabajador", new object[] {
                        request}, this.actualizarTrabajadorOperationCompleted, userState);
        }
        
        private void OnactualizarTrabajadorOperationCompleted(object arg) {
            if ((this.actualizarTrabajadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarTrabajadorCompleted(this, new actualizarTrabajadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.servicesweb.rrhhintegration.com/")]
    public partial class trabajador {
        
        private string apeMatField;
        
        private string apePatField;
        
        private string codigoAFPField;
        
        private string codigoBancoAbonoField;
        
        private string codigoDNIField;
        
        private string codigoDepartamentoField;
        
        private string codigoDistritoField;
        
        private string codigoNacionalidadField;
        
        private string codigoProvinciaField;
        
        private string direccionField;
        
        private string estadoCivilField;
        
        private string estadoPersonaField;
        
        private string nombresField;
        
        private string numCUPSField;
        
        private string sexoColaboradorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apeMat {
            get {
                return this.apeMatField;
            }
            set {
                this.apeMatField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apePat {
            get {
                return this.apePatField;
            }
            set {
                this.apePatField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoAFP {
            get {
                return this.codigoAFPField;
            }
            set {
                this.codigoAFPField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoBancoAbono {
            get {
                return this.codigoBancoAbonoField;
            }
            set {
                this.codigoBancoAbonoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoDNI {
            get {
                return this.codigoDNIField;
            }
            set {
                this.codigoDNIField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoDistrito {
            get {
                return this.codigoDistritoField;
            }
            set {
                this.codigoDistritoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoNacionalidad {
            get {
                return this.codigoNacionalidadField;
            }
            set {
                this.codigoNacionalidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoPersona {
            get {
                return this.estadoPersonaField;
            }
            set {
                this.estadoPersonaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numCUPS {
            get {
                return this.numCUPSField;
            }
            set {
                this.numCUPSField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sexoColaborador {
            get {
                return this.sexoColaboradorField;
            }
            set {
                this.sexoColaboradorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registrarTrabajadorCompletedEventHandler(object sender, registrarTrabajadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarTrabajadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarTrabajadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void obtenerTodosCompletedEventHandler(object sender, obtenerTodosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTodosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTodosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trabajador[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trabajador[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void eliminarTrabajadorCompletedEventHandler(object sender, eliminarTrabajadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTrabajadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTrabajadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void actualizarTrabajadorCompletedEventHandler(object sender, actualizarTrabajadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarTrabajadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarTrabajadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591