//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRHH.WebServicePostulante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.servicesweb.rrhhintegration.com/", ConfigurationName="WebServicePostulante.TrabajadorWS")]
    public interface TrabajadorWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        string registrarTrabajador(RRHH.WebServicePostulante.trabajador trabajador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        RRHH.WebServicePostulante.trabajador obtenerUno(string codigoTrabajador);
        
        // CODEGEN: Parameter 'response' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        RRHH.WebServicePostulante.obtenerTodosResponse obtenerTodos(RRHH.WebServicePostulante.obtenerTodos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        string eliminarTrabajador(string codigoTrabajador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        string actualizarTrabajador(RRHH.WebServicePostulante.trabajador trabajador);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.servicesweb.rrhhintegration.com/")]
    public partial class trabajador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apeMatField;
        
        private string apePatField;
        
        private string codigoAFPField;
        
        private string codigoBancoAbonoField;
        
        private string codigoDNIField;
        
        private string codigoDepartamentoField;
        
        private string codigoDistritoField;
        
        private string codigoNacionalidadField;
        
        private string codigoProvinciaField;
        
        private string correoField;
        
        private string direccionField;
        
        private string estadoActivoField;
        
        private string estadoCivilField;
        
        private string nombresField;
        
        private string numCUPSField;
        
        private string sexoColaboradorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apeMat {
            get {
                return this.apeMatField;
            }
            set {
                this.apeMatField = value;
                this.RaisePropertyChanged("apeMat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apePat {
            get {
                return this.apePatField;
            }
            set {
                this.apePatField = value;
                this.RaisePropertyChanged("apePat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoAFP {
            get {
                return this.codigoAFPField;
            }
            set {
                this.codigoAFPField = value;
                this.RaisePropertyChanged("codigoAFP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoBancoAbono {
            get {
                return this.codigoBancoAbonoField;
            }
            set {
                this.codigoBancoAbonoField = value;
                this.RaisePropertyChanged("codigoBancoAbono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoDNI {
            get {
                return this.codigoDNIField;
            }
            set {
                this.codigoDNIField = value;
                this.RaisePropertyChanged("codigoDNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
                this.RaisePropertyChanged("codigoDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoDistrito {
            get {
                return this.codigoDistritoField;
            }
            set {
                this.codigoDistritoField = value;
                this.RaisePropertyChanged("codigoDistrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoNacionalidad {
            get {
                return this.codigoNacionalidadField;
            }
            set {
                this.codigoNacionalidadField = value;
                this.RaisePropertyChanged("codigoNacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string codigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
                this.RaisePropertyChanged("codigoProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string estadoActivo {
            get {
                return this.estadoActivoField;
            }
            set {
                this.estadoActivoField = value;
                this.RaisePropertyChanged("estadoActivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string numCUPS {
            get {
                return this.numCUPSField;
            }
            set {
                this.numCUPSField = value;
                this.RaisePropertyChanged("numCUPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string sexoColaborador {
            get {
                return this.sexoColaboradorField;
            }
            set {
                this.sexoColaboradorField = value;
                this.RaisePropertyChanged("sexoColaborador");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTodos", WrapperNamespace="http://ws.servicesweb.rrhhintegration.com/", IsWrapped=true)]
    public partial class obtenerTodos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codigoTrabajador;
        
        public obtenerTodos() {
        }
        
        public obtenerTodos(string nombre, string codigoTrabajador) {
            this.nombre = nombre;
            this.codigoTrabajador = codigoTrabajador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTodosResponse", WrapperNamespace="http://ws.servicesweb.rrhhintegration.com/", IsWrapped=true)]
    public partial class obtenerTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RRHH.WebServicePostulante.trabajador[] response;
        
        public obtenerTodosResponse() {
        }
        
        public obtenerTodosResponse(RRHH.WebServicePostulante.trabajador[] response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrabajadorWSChannel : RRHH.WebServicePostulante.TrabajadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrabajadorWSClient : System.ServiceModel.ClientBase<RRHH.WebServicePostulante.TrabajadorWS>, RRHH.WebServicePostulante.TrabajadorWS {
        
        public TrabajadorWSClient() {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string registrarTrabajador(RRHH.WebServicePostulante.trabajador trabajador) {
            return base.Channel.registrarTrabajador(trabajador);
        }
        
        public RRHH.WebServicePostulante.trabajador obtenerUno(string codigoTrabajador) {
            return base.Channel.obtenerUno(codigoTrabajador);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RRHH.WebServicePostulante.obtenerTodosResponse RRHH.WebServicePostulante.TrabajadorWS.obtenerTodos(RRHH.WebServicePostulante.obtenerTodos request) {
            return base.Channel.obtenerTodos(request);
        }
        
        public RRHH.WebServicePostulante.trabajador[] obtenerTodos(string nombre, string codigoTrabajador) {
            RRHH.WebServicePostulante.obtenerTodos inValue = new RRHH.WebServicePostulante.obtenerTodos();
            inValue.nombre = nombre;
            inValue.codigoTrabajador = codigoTrabajador;
            RRHH.WebServicePostulante.obtenerTodosResponse retVal = ((RRHH.WebServicePostulante.TrabajadorWS)(this)).obtenerTodos(inValue);
            return retVal.response;
        }
        
        public string eliminarTrabajador(string codigoTrabajador) {
            return base.Channel.eliminarTrabajador(codigoTrabajador);
        }
        
        public string actualizarTrabajador(RRHH.WebServicePostulante.trabajador trabajador) {
            return base.Channel.actualizarTrabajador(trabajador);
        }
    }
}
